[package]
name = "fps-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = {version = "4.5.51", features = ["derive"]}
fps-core = { path = "../fps-core" }
num-rational = "0.4.2"
num-traits = "0.2.19"
